module.exports = [
  {
    name: "Sanjay Patil",
    fullName: "Sanjay Balasaheb Patil",
    phone: "9823456781",
    mobile: "9823456781",
    email: "sanjay.patil@gmail.com",
    village: "Hamidwada",
    district: "Kolhapur",
    state: "Maharashtra",
    landSize: "4.5 Acres",
    crops: "Sugarcane, Paddy",
    cropTypes: ["sugarcane", "paddy", "rice"],
    soilType: "Black"
  },
  {
    name: "Ananda Shinde",
    fullName: "Ananda Ramchandra Shinde",
    phone: "9421234567",
    mobile: "9421234567",
    email: "ananda.shinde@rediffmail.com",
    village: "Bastawade",
    district: "Kolhapur",
    state: "Maharashtra",
    landSize: "3.2 Acres",
    crops: "Sugarcane, Soybean",
    cropTypes: ["sugarcane", "soybean"],
    soilType: "Clayey"
  },
  {
    name: "Vilas Jadhav",
    fullName: "Vilas Dinkar Jadhav",
    phone: "9156789012",
    mobile: "9156789012",
    email: "vilas.jadhav@gmail.com",
    village: "Bidri",
    district: "Kolhapur",
    state: "Maharashtra",
    landSize: "6.0 Acres",
    crops: "Sugarcane, Rice",
    cropTypes: ["sugarcane", "rice", "paddy"],
    soilType: "Alluvial"
  },
  {
    name: "Ramesh Pawar",
    fullName: "Ramesh Yashwant Pawar",
    phone: "9921543210",
    mobile: "9921543210",
    email: "ramesh.pawar@gmail.com",
    village: "Boravade",
    district: "Kolhapur",
    state: "Maharashtra",
    landSize: "2.8 Acres",
    crops: "Soybean, Wheat",
    cropTypes: ["soybean", "wheat"],
    soilType: "Loamy"
  },
  {
    name: "Dattatray Deshmukh",
    fullName: "Dattatray Krishnarao Deshmukh",
    phone: "9890123456",
    mobile: "9890123456",
    email: "datta.deshmukh@gmail.com",
    village: "Sangaon",
    district: "Kolhapur",
    state: "Maharashtra",
    landSize: "5.5 Acres",
    crops: "Sugarcane, Groundnut",
    cropTypes: ["sugarcane", "groundnut"],
    soilType: "Black"
  },
  {
    name: "Sunil Mane",
    fullName: "Sunil Hindurao Mane",
    phone: "9765432109",
    mobile: "9765432109",
    email: "sunil.mane@yahoo.com",
    village: "Sulgaon",
    district: "Kolhapur",
    state: "Maharashtra",
    landSize: "2.1 Acres",
    crops: "Vegetables, Tomato",
    cropTypes: ["vegetable", "tomato"],
    soilType: "Loamy"
  },
  {
    name: "Tukaram Kamble",
    fullName: "Tukaram Maruti Kamble",
    phone: "8888765432",
    mobile: "8888765432",
    email: "tukaram.kamble@gmail.com",
    village: "Pimpalgaon",
    district: "Kolhapur",
    state: "Maharashtra",
    landSize: "3.7 Acres",
    crops: "Paddy, Chilli",
    cropTypes: ["paddy", "rice", "chilli"],
    soilType: "Clayey"
  },
  {
    name: "Suresh Sutar",
    fullName: "Suresh Ganpati Sutar",
    phone: "9011223344",
    mobile: "9011223344",
    email: "suresh.sutar@gmail.com",
    village: "Sidhanerli",
    district: "Kolhapur",
    state: "Maharashtra",
    landSize: "1.8 Acres",
    crops: "Chilli, Vegetables",
    cropTypes: ["chilli", "vegetable"],
    soilType: "Red"
  },
  {
    name: "Vijay Naik",
    fullName: "Vijay Shivajirao Naik",
    phone: "9145678901",
    mobile: "9145678901",
    email: "vijay.naik@gmail.com",
    village: "Shendur",
    district: "Kolhapur",
    state: "Maharashtra",
    landSize: "4.0 Acres",
    crops: "Sugarcane, Maize",
    cropTypes: ["sugarcane", "maize", "corn"],
    soilType: "Black"
  },
  {
    name: "Prakash Bhoite",
    fullName: "Prakash Baburao Bhoite",
    phone: "9673451298",
    mobile: "9673451298",
    email: "prakash.bhoite@gmail.com",
    village: "Vhannur",
    district: "Kolhapur",
    state: "Maharashtra",
    landSize: "3.0 Acres",
    crops: "Soybean, Maize",
    cropTypes: ["soybean", "maize", "corn"],
    soilType: "Loamy"
  },
  {
    name: "Sadashiv Sawant",
    fullName: "Sadashiv Ganpat Sawant",
    phone: "9422019283",
    mobile: "9422019283",
    email: "sadashiv.sawant@outlook.com",
    village: "Yamage",
    district: "Kolhapur",
    state: "Maharashtra",
    landSize: "5.0 Acres",
    crops: "Sugarcane, Paddy",
    cropTypes: ["sugarcane", "paddy", "rice"],
    soilType: "Black"
  },
  {
    name: "Babasaheb Ghatage",
    fullName: "Babasaheb Ramchandra Ghatage",
    phone: "9860123490",
    mobile: "9860123490",
    email: "baba.ghatage@gmail.com",
    village: "Kaulage",
    district: "Kolhapur",
    state: "Maharashtra",
    landSize: "7.5 Acres",
    crops: "Sugarcane, Cotton",
    cropTypes: ["sugarcane", "cotton"],
    soilType: "Black"
  },
  {
    name: "Raju Mohite",
    fullName: "Raju Dnyandev Mohite",
    phone: "9960784512",
    mobile: "9960784512",
    email: "raju.mohite@gmail.com",
    village: "Savarde",
    district: "Kolhapur",
    state: "Maharashtra",
    landSize: "3.4 Acres",
    crops: "Wheat, Soybean",
    cropTypes: ["wheat", "soybean"],
    soilType: "Loamy"
  },
  {
    name: "Deepak Chougule",
    fullName: "Deepak Appaso Chougule",
    phone: "9552123456",
    mobile: "9552123456",
    email: "deepak.chougule@gmail.com",
    village: "Gorambe",
    district: "Kolhapur",
    state: "Maharashtra",
    landSize: "4.2 Acres",
    crops: "Sugarcane, Vegetables",
    cropTypes: ["sugarcane", "vegetable"],
    soilType: "Black"
  }
];
