module.exports = [
  // FERTILIZERS
  {
    name: "IFFCO Urea Fertilizer",
    categoryName: "Fertilizers",
    supplierName: "IFFCO Fertilizers Ltd",
    unit: "bag",
    price: 300,
    purchasePrice: 240,
    sellingPrice: 300,
    reorderLevel: 25,
    description: "High quality nitrogen fertilizer containing 46% nitrogen. Essential for sugarcane, paddy, and wheat crop growth during monsoon.",
    keywords: ["urea", "nitrogen", "sugarcane", "paddy", "monsoon"],
    batchNumber: "UR-2025-09",
    stockStatus: "Fresh"
  },
  {
    name: "IFFCO NPK 19-19-19",
    categoryName: "Fertilizers",
    supplierName: "IFFCO Fertilizers Ltd",
    unit: "bag",
    price: 1200,
    purchasePrice: 950,
    sellingPrice: 1200,
    reorderLevel: 15,
    description: "Balanced water-soluble NPK fertilizer for sugarcane, wheat, and vegetables. Excellent slow-release potash, phosphorus, and nitrogen booster.",
    keywords: ["npk", "potash", "sugarcane", "wheat", "rice", "winter", "slow-release"],
    batchNumber: "NPK-2025-04",
    stockStatus: "Fresh"
  },
  {
    name: "IFFCO DAP (Di-Ammonium Phosphate)",
    categoryName: "Fertilizers",
    supplierName: "IFFCO Fertilizers Ltd",
    unit: "bag",
    price: 1350,
    purchasePrice: 1100,
    sellingPrice: 1350,
    reorderLevel: 20,
    description: "DAP fertilizer providing phosphorus and nitrogen. Excellent for soybean, wheat, and cotton root development and soil enrichment.",
    keywords: ["dap", "phosphate", "soybean", "wheat", "cotton"],
    batchNumber: "DAP-2025-11",
    stockStatus: "Fresh"
  },
  {
    name: "Mahadhan Superphos Potash",
    categoryName: "Fertilizers",
    supplierName: "Mahadhan Fertilizers",
    unit: "bag",
    price: 850,
    purchasePrice: 680,
    sellingPrice: 850,
    reorderLevel: 10,
    description: "Premium potash fertilizer to improve sugar content in sugarcane and drought tolerance in summer crops.",
    keywords: ["potash", "sugarcane", "slow-release", "summer"],
    batchNumber: "POT-2025-03",
    stockStatus: "Fresh"
  },
  {
    name: "AgriGypsum Soil Conditioner",
    categoryName: "Fertilizers",
    supplierName: "Kolhapur District Agri Tools & Implements",
    unit: "bag",
    price: 450,
    purchasePrice: 320,
    sellingPrice: 450,
    reorderLevel: 5,
    description: "Gypsum amendment for Clayey soil to improve drainage, soil aeration, and calcium levels.",
    keywords: ["gypsum", "clayey", "conditioner"],
    batchNumber: "GYP-2025-01",
    stockStatus: "Fresh"
  },
  {
    name: "Agricultural Lime Calcium Boost",
    categoryName: "Fertilizers",
    supplierName: "Mahadhan Fertilizers",
    unit: "bag",
    price: 500,
    purchasePrice: 380,
    sellingPrice: 500,
    reorderLevel: 8,
    description: "Soil amendment lime for Laterite and Red soil to balance pH and supply calcium.",
    keywords: ["lime", "calcium", "laterite", "red"],
    batchNumber: "LIM-2025-02",
    stockStatus: "Fresh"
  },

  // SEEDS
  {
    name: "Mahyco Cotton Seed Gold",
    categoryName: "Seeds",
    supplierName: "Mahyco Seeds Co",
    unit: "bag",
    price: 860,
    purchasePrice: 720,
    sellingPrice: 860,
    reorderLevel: 30,
    description: "High-yield Bt cotton seed suitable for black soil. Highly resistant to sucking pests.",
    keywords: ["cotton", "seed"],
    batchNumber: "COT-SD-2025",
    stockStatus: "Fresh"
  },
  {
    name: "Mahyco Sugarcane Buds (Co 86032)",
    categoryName: "Seeds",
    supplierName: "Mahyco Seeds Co",
    unit: "piece",
    price: 5,
    purchasePrice: 3.5,
    sellingPrice: 5,
    reorderLevel: 100,
    description: "Healthy sugarcane planting setts/buds for monsoon sowing.",
    keywords: ["sugarcane", "seed"],
    batchNumber: "SUG-BD-2025",
    stockStatus: "Fresh"
  },
  {
    name: "Bayer Paddy Rice Seed Arize",
    categoryName: "Seeds",
    supplierName: "Bayer CropScience India",
    unit: "bag",
    price: 650,
    purchasePrice: 520,
    sellingPrice: 650,
    reorderLevel: 20,
    description: "Hybrid rice/paddy seed with high yield and disease resistance. Best sown in monsoon.",
    keywords: ["rice", "paddy", "seed", "monsoon"],
    batchNumber: "PADDY-ARI-25",
    stockStatus: "Fresh"
  },
  {
    name: "Mahyco Wheat Seed Kanchan",
    categoryName: "Seeds",
    supplierName: "Mahyco Seeds Co",
    unit: "bag",
    price: 950,
    purchasePrice: 780,
    sellingPrice: 950,
    reorderLevel: 15,
    description: "High grain quality wheat seed, perfect for winter sowing.",
    keywords: ["wheat", "seed", "winter"],
    batchNumber: "WHT-KNC-25",
    stockStatus: "Fresh"
  },
  {
    name: "Soybean Seed JS-335",
    categoryName: "Seeds",
    supplierName: "Mahyco Seeds Co",
    unit: "bag",
    price: 1800,
    purchasePrice: 1500,
    sellingPrice: 1800,
    reorderLevel: 12,
    description: "Early maturing soybean seed, high germination rate. Best for loamy/red soil.",
    keywords: ["soybean", "seed"],
    batchNumber: "SOY-335-25",
    stockStatus: "Fresh"
  },
  {
    name: "Hybrid Tomato Seed Abhinav",
    categoryName: "Seeds",
    supplierName: "Bayer CropScience India",
    unit: "box",
    price: 350,
    purchasePrice: 280,
    sellingPrice: 350,
    reorderLevel: 10,
    description: "High-yield tomato seeds suitable for summer/winter cultivation.",
    keywords: ["tomato", "seed", "vegetable"],
    batchNumber: "TOM-ABH-25",
    stockStatus: "Fresh"
  },
  {
    name: "Tejaswini Chilli Seed",
    categoryName: "Seeds",
    supplierName: "Mahyco Seeds Co",
    unit: "box",
    price: 250,
    purchasePrice: 190,
    sellingPrice: 250,
    reorderLevel: 10,
    description: "Spicy chilli hybrid seeds for red/loamy soils.",
    keywords: ["chilli", "seed", "vegetable"],
    batchNumber: "CHL-TEJ-25",
    stockStatus: "Fresh"
  },

  // INSECTICIDES
  {
    name: "Bayer Confidor Insecticide",
    categoryName: "Insecticides",
    supplierName: "Bayer CropScience India",
    unit: "litre",
    price: 1600,
    purchasePrice: 1300,
    sellingPrice: 1600,
    reorderLevel: 8,
    description: "Contains imidacloprid for controlling sucking pests in cotton and vegetables.",
    keywords: ["imidacloprid", "insecticide", "cotton"],
    batchNumber: "CONF-998",
    stockStatus: "Fresh"
  },
  {
    name: "Rallis Chlorpyrifos 20% EC",
    categoryName: "Insecticides",
    supplierName: "Rallis India Limited (A Tata Enterprise)",
    unit: "litre",
    price: 550,
    purchasePrice: 420,
    sellingPrice: 550,
    reorderLevel: 10,
    description: "Broad-spectrum insecticide for cotton, paddy, and sugarcane soil pest control.",
    keywords: ["chlorpyrifos", "insecticide", "cotton", "rice", "paddy"],
    batchNumber: "CHL-456",
    stockStatus: "Fresh"
  },

  // PESTICIDES
  {
    name: "Rallis Contaf Fungicide",
    categoryName: "Pesticides",
    supplierName: "Rallis India Limited (A Tata Enterprise)",
    unit: "litre",
    price: 800,
    purchasePrice: 650,
    sellingPrice: 800,
    reorderLevel: 8,
    description: "Fungicide to prevent rust and leaf spot in wheat and vegetables during winter and monsoon rain.",
    keywords: ["fungicide", "rust", "wheat", "monsoon", "winter", "rain"],
    batchNumber: "CONT-887",
    stockStatus: "Fresh"
  },
  {
    name: "Neem Oil Organic Pest Control",
    categoryName: "Pesticides",
    supplierName: "Rallis India Limited (A Tata Enterprise)",
    unit: "litre",
    price: 400,
    purchasePrice: 300,
    sellingPrice: 400,
    reorderLevel: 5,
    description: "Organic cold-pressed neem oil pesticide for vegetable, tomato, and chilli crops.",
    keywords: ["neem", "oil", "pesticide", "vegetable", "tomato", "chilli"],
    batchNumber: "NEEM-002",
    stockStatus: "Fresh"
  },
  {
    name: "Roundup Weedicide Herbicide",
    categoryName: "Pesticides",
    supplierName: "Bayer CropScience India",
    unit: "litre",
    price: 700,
    purchasePrice: 550,
    sellingPrice: 700,
    reorderLevel: 10,
    description: "Broad-spectrum systemic herbicide for soybean and sugarcane weed control.",
    keywords: ["weedicide", "soybean", "sugarcane", "monsoon"],
    batchNumber: "RND-771",
    stockStatus: "Fresh"
  },

  // TOOLS
  {
    name: "Farming Hand Sickle Steel",
    categoryName: "Farming Tools",
    supplierName: "Kolhapur District Agri Tools & Implements",
    unit: "piece",
    price: 150,
    purchasePrice: 90,
    sellingPrice: 150,
    reorderLevel: 15,
    description: "Ergonomic steel hand sickle for harvesting paddy, wheat, and sugarcane.",
    keywords: ["sickle", "implement", "tool"],
    batchNumber: "TOL-SC-01",
    stockStatus: "Fresh"
  },
  {
    name: "Farming Hoe Iron Grip",
    categoryName: "Farming Tools",
    supplierName: "Kolhapur District Agri Tools & Implements",
    unit: "piece",
    price: 350,
    purchasePrice: 220,
    sellingPrice: 350,
    reorderLevel: 10,
    description: "High-quality iron hoe with wooden handle for weeding and soil loosening.",
    keywords: ["hoe", "tool"],
    batchNumber: "TOL-HO-02",
    stockStatus: "Fresh"
  },
  {
    name: "Knapsack Battery Power Sprayer",
    categoryName: "Farming Tools",
    supplierName: "Kolhapur District Agri Tools & Implements",
    unit: "piece",
    price: 3800,
    purchasePrice: 2900,
    sellingPrice: 3800,
    reorderLevel: 4,
    description: "16-litre capacity battery-operated sprayer for insecticides, pesticides, and neem oil.",
    keywords: ["sprayer", "tool"],
    batchNumber: "TOL-SP-03",
    stockStatus: "Fresh"
  }
];
